### PR TITLE
ci: fix CI failure 

### PR DESCRIPTION
**Pull request by alxiong**
Changes include:

- Pin jellyfish at [`bcd92b2`](https://github.com/EspressoSystems/jellyfish/commit/bcd92b2cffd63b946a6b11c327ef1f5efb957714)
- migrate to `flake`, removed cargo-husky (since already using precommit hook in flake) and update README. 
- add missing generic param in non-bn254-feature code, fixing slow test
- fix clippy errors.

### CODE REVIEW

**Comment by mrain** [comment]
Shall we consider remove `Cargo.lock`? As this is a library crate, and we pinned to the commits.

I tried, but encountered some issue with `espresso_systems_common::jellyfish::tag`.

**Comment by alxiong** [comment]
There are binaries in this repo, such as gen-params. 

Also I vaguely recall Nathan suggesting to commit lock file even for library for better reproducibility and avoid version conflict in dep that's hard to debug.

**Review by mrain — APPROVED** [review]
LGTM.

**Review by Ancient123 — APPROVED** [review]

**Comment by mrain** [comment]
> There are binaries in this repo, such as gen-params.
> 
> Also I vaguely recall Nathan suggesting to commit lock file even for library for **better reproducibility and avoid version conflict in dep that's hard to debug.**
> 
> (I'm also open to any idea if there's good evidence)

Good point, the problem with `espresso-systems-common` seems hard to fix.

**Comment by chancharles92** [comment]
https://github.com/EspressoSystems/cap/actions/runs/5488929132/jobs/10002431609
Any clue on why it's still not compiling in main?

**Comment by mrain** [comment]
Feels weird to use `ark_bls12_381::Bls12_377`. Is it a typo before?

**Comment by chancharles92** [comment]
96336e8822a9672c107a05e39cf7ec9fe897f2ea
Seems this commit last year is not compiling either cc @alxiong

**Comment by Ancient123** [comment]
`error[E0412]: cannot find type `Bls12_377` in crate `ark_bls12_381` `

**Comment by Ancient123** [comment]
Also we need to turn off `-Zunstable-options --report-time` on the tests before it will run tests with current rust versions.

**Comment by alxiong** [comment]
Ah sorry! I'll fix that today!

**Pull request merged**
